### ISSUE TITLE
way old AES.class.php

### ISSUE THREAD

**Issue by andyknas** [phillipsdata/phpaes#4]
I have your way old class from Oct 1, 2007.  This older class doesn't seem to be compatible with other libraries to decrypt AES128 not was i able to just drop in this newer class to replace it. I'm thinking i need to decrypt with the older class and then re-encrypt with the newer one to get some compatibility?

**Comment by clphillips** [comment]
This class may not be a drop in replacement due to PHP namespace changed and possibly some method signature changed, but it should have no problem decrypting data encrypted using the old class, provided you provide the same key, initialization vector, mode, and padding scheme required by this version of the class.

If you could replicate the issue with some example data, that would be a big help. For example, encrypt "hello world" with your old copy andnew copy with the same options.
